name: Make NDK (musl libc)
run-name: Make NDK-r${{inputs.ndk_version}} with llvm-${{inputs.llvm_version}}-musl
on:
  workflow_dispatch:
    inputs:
      ndk_version:
        description: "NDK Release version:"
        default: '29-beta1'
        required: true
        type: string
      llvm_version:
        description: "LLVM Release version:"
        default: '20.1.0'
        required: true
        type: string

jobs:
  make:
    name: Make NDK musl
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target: [aarch64-linux-musl, x86_64-linux-musl]
    steps:
      - name: Get NDK and LLVM
        run: |
          curl -LkSs https://dl.google.com/android/repository/android-ndk-r${{inputs.ndk_version}}-linux.zip >ndk.zip && unzip -q ndk.zip
          curl -LkSs https://github.com/MobilePorting/android-ndk-cosmo/releases/download/llvm/clang+clang-tools-extra+lld-${{inputs.llvm_version}}-${{matrix.target}}.tar.xz | tar -xJf -

      - name: Make NDK musl
        run: |
          NDK="${PWD}/android-ndk-r${{inputs.ndk_version}}"
          HOST_TOOLCHAIN="${PWD}/clang+clang-tools-extra+lld-${{inputs.llvm_version}}-${{matrix.target}}"
          NDK_TOOLCHAIN="${NDK}/toolchains/llvm/prebuilt/linux-x86_64"

          find "${NDK_TOOLCHAIN}/bin" -type f | while IFS= read -r file; do
              bname="$(basename "${file}")"
              if [ -f "${HOST_TOOLCHAIN}/bin/${bname}" ] && file "${file}" | grep -q 'ELF'; then
                  echo "Replacing ${bname}"
                  cp "${HOST_TOOLCHAIN}/bin/${bname}" "${file}"
              elif file "${file}" | grep -q 'Bourne-Again shell script'; then
                  echo "Replacing SheBang ${bname}"
                  sed -i 's,#!/usr/bin/env bash,#!/usr/bin/env sh,' "${file}"
              fi

              if file "${file}" | grep -q 'ELF'; then
                  echo "Removing ${bname}"
                  rm ${file}
              fi
          done

          ## Fix: ERROR: Unknown host CPU architecture: aarch64
          sed -i 's/arm64)/arm64|aarch64)/' "${NDK}/build/tools/ndk_bin_common.sh"

          ## Remove unused resource
          rm -rf "${NDK_TOOLCHAIN}/python3"
          rm -rf "${NDK_TOOLCHAIN}/musl"
          rm -rf "${NDK}/prebuilt/linux_x86-64/bin/*asm"
          find "${NDK_TOOLCHAIN}/lib" -maxdepth 1 -mindepth 1 -not -name clang -exec rm -rf {} \;
          find "${NDK_TOOLCHAIN}" -maxdepth 5 -path "*/lib/clang/[0-9][0-9]/lib/*" -not -name linux -exec rm -rf {} \;

          curl -LkSs https://cosmo.zip/pub/cosmos/bin/make > "${NDK}/prebuilt/linux-x86_64/bin/make" && chmod +x "${NDK}/prebuilt/linux-x86_64/bin/make"
          mkdir -p "${NDK_TOOLCHAIN}/python3/bin"
          curl -LkSs https://cosmo.zip/pub/cosmos/bin/python >"${NDK_TOOLCHAIN}/python3/bin/python3" && chmod +x "${NDK_TOOLCHAIN}/python3/bin/python3"

          if [ "${{ matrix.target }}" = "aarch64-linux-musl" ]; then
              mv ${NDK}/prebuilt/linux-x86_64 ${NDK}/prebuilt/linux-arm64
              mv ${NDK}/toolchains/llvm/prebuilt/linux-x86_64 ${NDK}/toolchains/llvm/prebuilt/linux-arm64
          fi

          rm -rf ${NDK}/shader-tools # TODO: maybe build?

      - name: Archive
        run: tar -cf - android-ndk-r${{inputs.ndk_version}} | xz -T0 -9e --lzma2=dict=256MiB > android-ndk-r${{inputs.ndk_version}}-${{matrix.target}}.tar.xz

      - uses: actions/upload-artifact@v4
        with:
          name: android-ndk-r${{inputs.ndk_version}}-${{matrix.target}}
          path: android-ndk-r${{inputs.ndk_version}}-${{matrix.target}}.tar.xz

  release:
    needs: [make]
    name: Release
    permissions:
      contents: write
      actions: write
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true

    - name: Release
      uses: ncipollo/release-action@v1.15.0
      with:
        tag: "r${{inputs.ndk_version}}"
        artifacts: android-ndk-r${{inputs.ndk_version}}*
        allowUpdates: true
        replacesArtifacts: true
        body: |
          [action](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}})
